version: "3.8"
name: osu-framework

services:
  # 数据库
  sp-db:
    container_name: sp-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: sp
      POSTGRES_USER: sp
      POSTGRES_PASSWORD: "password_is0*001."
    volumes:
      - "${PWD}/database:/var/lib/postgresql/data"
  # 应用
  sp-app:
    container_name: sp-app
    build:
      context: .
      args:
        - PORT=8080
        - DATABASE_URL=jdbc:postgresql://sp-db:5432/sp
        - DATABASE_USERNAME=sp
        - DATABASE_PASSWORD=password_is0*001.
    ports:
      - "8080:8080"
    depends_on:
      - sp-db
    volumes:
      - "${PWD}:/app/"