[package]
name = "spring-jni"
version = "0.0.1"
edition = "2021"


[lib]
crate-type = ['cdylib']

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1

[features]

[dependencies]
jni-macro = { version = "0.0.1", path = "jni_macro" }
jni = "0.21.1"
#rosu-pp = "1.1.0"
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp.git", branch = "pp-update" }
thiserror = "1.0.68"
