[package]
name = "spring-jni"
version = "0.0.1"
edition = "2021"


[lib]
crate-type = ['cdylib']

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
[features]
[dependencies]
bytes = "1.7.2"
jni = "0.21.1"
paste = "1.0.15"
rosu-pp = "1.1.0"
thiserror = "1.0.64"
